name: Production Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Run Backend Smoke Tests
        run: node tests/smoke.js

      - name: Build and Release Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Used for code signing the windows installer to ensure artifact verification
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        run: npm run dist -- --publish always
